# Generated by Django 6.0.2 on 2026-02-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('url', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
            ],
        ),
    ]
