# Generated by Django 6.0.2 on 2026-02-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='belonging_url',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
