# Generated by Django 6.0.2 on 2026-02-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0003_textentry_belonging_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textentry',
            name='visibility',
            field=models.CharField(default='PUBLIC', max_length=20),
        ),
    ]
