# Generated by Django 6.0.2 on 2026-03-01 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_distribution", "0005_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="liked_object",
            new_name="object",
        ),
    ]
