# Generated by Django 6.0.2 on 2026-03-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='content_type',
            field=models.CharField(choices=[('text/markdown', 'CommonMark'), ('text/plain', 'PLain Text')], default='text/plain', max_length=50),
        ),
    ]
