# Generated by Django 6.0.2 on 2026-03-01 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0006_rename_liked_object_like_object'),
        ('social_distribution', '0006_textentry_content_type'),
    ]

    operations = [
    ]
