# Generated by Django 6.0.2 on 2026-03-01 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0007_merge_20260301_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='timestamp',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='textentry',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'PLain Text'), ('text/markdown', 'CommonMark')], default='text/plain', max_length=50),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='social_distribution.author')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='social_distribution.author')),
            ],
        ),
    ]
