# Generated by Django 6.0.2 on 2026-03-01 23:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_distribution", "0008_rename_timestamp_like_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textentry",
            name="content_type",
            field=models.CharField(
                choices=[("text/markdown", "CommonMark"), ("text/plain", "PLain Text")],
                default="text/plain",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="textentry",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date published"
            ),
        ),
    ]
