# Generated by Django 6.0.2 on 2026-03-02 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_distribution", "0009_alter_textentry_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textentry",
            name="content_type",
            field=models.CharField(
                choices=[("text/plain", "PLain Text"), ("text/markdown", "CommonMark")],
                default="text/plain",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "content_type",
                    models.CharField(default="text/markdown", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_distribution.author",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="social_distribution.textentry",
                    ),
                ),
            ],
        ),
    ]
