# Generated by Django 6.0.2 on 2026-03-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0010_alter_textentry_content_type_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textentry',
            name='content_type',
            field=models.CharField(choices=[('text/markdown', 'CommonMark'), ('text/plain', 'PLain Text')], default='text/plain', max_length=50),
        ),
    ]
