# Generated by Django 6.0.2 on 2026-03-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0010_alter_textentry_content_type_comment'),
        ('social_distribution', '0010_textentry_visibility'),
    ]

    operations = [
    ]
