# Generated by Django 6.0.2 on 2026-03-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_distribution", "0012_alter_textentry_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textentry",
            name="content_type",
            field=models.CharField(
                choices=[("text/markdown", "CommonMark"), ("text/plain", "Plain Text")],
                default="text/plain",
                max_length=50,
            ),
        ),
    ]
