# Generated by Django 6.0.2 on 2026-03-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0013_alter_textentry_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textentry',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'CommonMark')], default='text/plain', max_length=50),
        ),
    ]
