# Generated by Django 6.0.2 on 2026-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0015_alter_author_description_alter_author_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='author',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
    ]
