# Generated by Django 6.0.2 on 2026-03-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0016_author_host_author_is_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
