# Generated by Django 6.0.2 on 2026-03-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0017_author_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='github_last_polled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
