# Generated by Django 6.0.2 on 2026-03-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0018_author_github_last_polled'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='source_type',
            field=models.CharField(choices=[('native', 'Native'), ('github', 'GitHub')], default='native', max_length=20),
        ),
    ]
