# Generated by Django 6.0.2 on 2026-03-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0019_textentry_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entries/'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'CommonMark'), ('image/png', 'PNG Image'), ('image/jpeg', 'JPEG Image'), ('image/gif', 'GIF Image')], default='text/plain', max_length=50),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='entry_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
