# Generated by Django 6.0.2 on 2026-03-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0020_textentry_image_alter_textentry_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='entry_header',
            field=models.CharField(default=''),
        ),
    ]
