# Generated by Django 6.0.3 on 2026-03-18 22:03
 
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models
 
 
class Migration(migrations.Migration):
 
    initial = True
 
    dependencies = []
 
    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.URLField(max_length=500, primary_key=True, serialize=False)),
                ('serial', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('host', models.URLField(blank=True, default='', max_length=500)),
                ('is_local', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('picture', models.CharField(blank=True, default='', max_length=200)),
                ('github', models.CharField(blank=True, default='', max_length=200)),
                ('github_last_polled', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='social_distribution.author')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='social_distribution.author')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_url', models.URLField(max_length=500)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social_distribution.author')),
            ],
        ),
        migrations.CreateModel(
            name='TextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='entries/')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'CommonMark'), ('image/png', 'PNG Image'), ('image/jpeg', 'JPEG Image'), ('image/gif', 'GIF Image')], default='text/plain', max_length=50)),
                ('source_type', models.CharField(choices=[('native', 'Native'), ('github', 'GitHub')], default='native', max_length=10)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted')], default='PUBLIC', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='social_distribution.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.URLField(max_length=500)),
                ('comment', models.TextField()),
                ('content_type', models.CharField(default='text/markdown', max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social_distribution.author')),
                ('local_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_on', to='social_distribution.textentry')),
            ],
        ),
    ]
 