# Generated by Django 6.0.2 on 2026-03-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0022_standardized_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('password', models.CharField(blank=True, default='', max_length=150)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='textentry',
            name='remote_fqid',
            field=models.URLField(blank=True, db_index=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted'), ('DELETED', 'Deleted')], default='PUBLIC', max_length=20),
        ),
    ]
