# Generated by Django 6.0.2 on 2026-03-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0023_node_textentry_remote_fqid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='password',
            new_name='incoming_password',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='username',
            new_name='incoming_username',
        ),
        migrations.AddField(
            model_name='node',
            name='outgoing_password',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='node',
            name='outgoing_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
