# Generated by Django 6.0.2 on 2026-03-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0024_rename_password_node_incoming_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='remote_fqid',
            field=models.URLField(blank=True, db_index=True, default='', max_length=500),
        ),
    ]
