# Generated by Django 6.0.2 on 2026-03-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0025_comment_remote_fqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='web',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
