# Generated by Django 6.0.2 on 2026-03-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0026_author_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textentry',
            name='image',
        ),
        migrations.AlterField(
            model_name='textentry',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'CommonMark'), ('image/png;base64', 'PNG Image'), ('image/jpeg;base64', 'JPEG Image'), ('application/base64', 'Generic Binary Image')], default='text/plain', max_length=50),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='source_type',
            field=models.CharField(choices=[('native', 'Native'), ('github', 'GitHub'), ('remote', 'Remote')], default='native', max_length=10),
        ),
    ]
